Repository ssg-240304-java2/wms-albumshop, pull requests merged in 2024-05, with the labels that each got.

#1 MyBatis 설정 파일 추가, 클래스명 자바 컨벤션에 맞게 변경, 패키지 위치 변경
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/wms-albumshop.iml
  albumshop/src/main/java/bangshop/music/Application.java
  albumshop/src/main/java/bangshop/music/common/error/ErrorCode.java
  albumshop/src/main/java/bangshop/music/common/error/ErrorView.java
  albumshop/src/main/java/bangshop/music/view/menu/MainMenu.java
  albumshop/src/main/resources/config/connection-info.properties
  albumshop/src/main/resources/template/JDBCTemplate.java
  albumshop/src/main/resources/template/mybatis-config.xml
Labels: bug

#20 #17 - 창고관리자 메뉴 구현
  albumshop/src/main/java/bangshop/music/common/utils/IOUtils.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminMenu.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
Labels: Feature

#22 mybatis template추가 및 파일 수정
  .idea/misc.xml
  albumshop/src/main/java/bangshop/music/common/MyBatisTemplate.java
  albumshop/src/main/java/bangshop/music/controller/Controller.java
  albumshop/src/main/java/bangshop/music/model/dao/dao.java
  albumshop/src/main/java/bangshop/music/model/service/Service.java
  albumshop/src/main/java/bangshop/music/view/menu/StoreManagerMenu.java
  albumshop/src/main/java/bangshop/music/view/menu/StoreManagerView.java
Labels: Feature

#23 #2 #5 #6 계정 생성, 로그인, 로그아웃 기능 구현
  albumshop/src/main/java/bangshop/music/Application.java
  albumshop/src/main/java/bangshop/music/controller/EmployeeController.java
  albumshop/src/main/java/bangshop/music/model/dao/EmployeeMapper.java
  albumshop/src/main/java/bangshop/music/model/dto/EmployeeDTO.java
  albumshop/src/main/java/bangshop/music/model/dto/Role.java
  albumshop/src/main/java/bangshop/music/model/service/EmployeeService.java
  albumshop/src/main/java/bangshop/music/view/menu/MainMenu.java
  albumshop/src/main/java/bangshop/music/view/menu/MainViewMenu.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
  albumshop/src/main/resources/mybatis-config.xml
  albumshop/src/main/resources/sql/mapper/cy-query.xml
Labels: Feature

#24 #12 - 출고 내역 조회
  albumshop/src/main/java/bangshop/music/controller/DispatchController.java
  albumshop/src/main/java/bangshop/music/model/StockOut.java
  albumshop/src/main/java/bangshop/music/model/StockOutStatus.java
  albumshop/src/main/java/bangshop/music/model/dao/StockOutMapper.java
  albumshop/src/main/java/bangshop/music/model/dto/OrderDTO.java
  albumshop/src/main/java/bangshop/music/model/dto/StockOutAndStorageDTO.java
  albumshop/src/main/java/bangshop/music/model/dto/StorageDTO.java
  albumshop/src/main/java/bangshop/music/model/dto/StoreDTO.java
  albumshop/src/main/java/bangshop/music/model/service/DispatchService.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
Labels: Feature

#31 Feat/album search
  albumshop/src/main/java/bangshop/music/controller/SearchController.java
  albumshop/src/main/java/bangshop/music/model/dao/SearchMapper.java
  albumshop/src/main/java/bangshop/music/model/dao/dao.java
  albumshop/src/main/java/bangshop/music/model/service/SearchService.java
  albumshop/src/main/java/bangshop/music/view/menu/StoreManagerView.java
  albumshop/src/main/java/bangshop/music/view/result/SearchResultView.java
  albumshop/src/main/resources/mybatis-config.xml
  albumshop/src/main/resources/sql/mapper/sc-query.xml
Labels: Feature

#32 #3 입고 기능 수정
  albumshop/src/main/java/bangshop/music/model/service/storageService.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
  albumshop/src/main/resources/sql/mapper/db-query.xml
Labels: bug

#34 출고 기능 구현 완료
  albumshop/src/main/java/bangshop/music/Application.java
  albumshop/src/main/java/bangshop/music/controller/DispatchController.java
  albumshop/src/main/java/bangshop/music/model/dao/AlbumMapper.java
  albumshop/src/main/java/bangshop/music/model/dao/AlbumStorageMapper.java
  albumshop/src/main/java/bangshop/music/model/dao/OrderMapper.java
  albumshop/src/main/java/bangshop/music/model/dao/StockOutMapper.java
  albumshop/src/main/java/bangshop/music/model/domain/StockOut.java
  albumshop/src/main/java/bangshop/music/model/domain/StockOutStatus.java
  albumshop/src/main/java/bangshop/music/model/dto/AlbumStorageDTO.java
  albumshop/src/main/java/bangshop/music/model/dto/StockOutAndStorageDTO.java
  albumshop/src/main/java/bangshop/music/model/dto/StorageDTO.java
  albumshop/src/main/java/bangshop/music/model/service/DispatchService.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
  albumshop/src/main/resources/mybatis-config.xml
  albumshop/src/main/resources/sql/mapper/album-storage-mapper.xml
  albumshop/src/main/resources/sql/mapper/order-mapper.xml
  albumshop/src/main/resources/sql/mapper/yr-query.xml
Labels: Feature

#35 #10 Feature search albums
  albumshop/src/main/java/bangshop/music/controller/SearchController.java
  albumshop/src/main/java/bangshop/music/model/dao/SearchMapper.java
  albumshop/src/main/java/bangshop/music/model/service/SearchService.java
  albumshop/src/main/java/bangshop/music/view/menu/StoreManagerView.java
  albumshop/src/main/java/bangshop/music/view/result/SearchResultView.java
  albumshop/src/main/resources/mybatis-config.xml
  albumshop/src/main/resources/sql/mapper/sc-query.xml
Labels: Feature

#36 #14, #8 11번은 하는중
  albumshop/src/main/java/bangshop/music/common/error/ErrorCode.java
  albumshop/src/main/java/bangshop/music/common/error/ErrorView.java
  albumshop/src/main/java/bangshop/music/controller/Controller.java
  albumshop/src/main/java/bangshop/music/controller/EmployeeController.java
  albumshop/src/main/java/bangshop/music/controller/OrderStorageController.java
  albumshop/src/main/java/bangshop/music/model/dao/OrderStorageMapper.java
  albumshop/src/main/java/bangshop/music/model/dao/dao.java
  albumshop/src/main/java/bangshop/music/model/dto/AlbumStorageDTO.java
  albumshop/src/main/java/bangshop/music/model/service/OrderStorageService.java
  albumshop/src/main/java/bangshop/music/model/service/Service.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
  albumshop/src/main/java/bangshop/music/view/menu/StoreManagerView.java
  albumshop/src/main/resources/mybatis-config.xml
  albumshop/src/main/resources/sql/mapper/jh-query.xml
Labels: bug

#38 #37 입고 재입력시에 무한 루프 버그 수정
  albumshop/src/main/java/bangshop/music/Application.java
  albumshop/src/main/java/bangshop/music/common/utils/IOUtils.java
  albumshop/src/main/java/bangshop/music/controller/StorageController.java
  albumshop/src/main/java/bangshop/music/model/service/StorageService.java
  albumshop/src/main/java/bangshop/music/view/PrintsResult.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
  albumshop/src/main/resources/sql/mapper/db-query.xml
Labels: bug

#43 #42 앨범 등록 기능 구현
  albumshop/src/main/java/bangshop/music/controller/StorageController.java
  albumshop/src/main/java/bangshop/music/model/dao/Mapper.java
  albumshop/src/main/java/bangshop/music/model/dto/AlbumDTO.java
  albumshop/src/main/java/bangshop/music/model/service/StorageService.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminMenu.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
  albumshop/src/main/resources/sql/mapper/db-query.xml
Labels: Feature

#45 OrderDto, AlbumStorageDTO toString 및 쿼리 수정
  albumshop/src/main/java/bangshop/music/Application.java
  albumshop/src/main/java/bangshop/music/model/dto/AlbumStorageDTO.java
  albumshop/src/main/java/bangshop/music/model/dto/OrderDTO.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
  albumshop/src/main/java/bangshop/music/view/menu/StoreManagerView.java
  albumshop/src/main/resources/sql/mapper/jh-query.xml
Labels: update

#51 앨범 등록 기능 에러 수정
  albumshop/src/main/java/bangshop/music/model/dao/AlbumMapper.java
  albumshop/src/main/java/bangshop/music/model/dao/StockInMapper.java
  albumshop/src/main/java/bangshop/music/model/service/StorageService.java
  albumshop/src/main/java/bangshop/music/view/PrintsResult.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
Labels: bug

#54 order
  albumshop/src/main/java/bangshop/music/controller/OrderController.java
  albumshop/src/main/java/bangshop/music/controller/SearchController.java
  albumshop/src/main/java/bangshop/music/model/dao/OrderMapper.java
  albumshop/src/main/java/bangshop/music/model/dao/SearchMapper.java
  albumshop/src/main/java/bangshop/music/model/service/OrderService.java
  albumshop/src/main/java/bangshop/music/model/service/SearchService.java
  albumshop/src/main/java/bangshop/music/view/menu/StoreManagerView.java
  albumshop/src/main/java/bangshop/music/view/result/SearchResultView.java
  albumshop/src/main/resources/mybatis-config.xml
  albumshop/src/main/resources/sql/mapper/sc-query.xml
  albumshop/src/main/resources/sql/mapper/sc2-query.xml
Labels: Feature

#55 메소드명 및 Parameter값 수정 테스트코드 업로드
  .idea/.gitignore
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/wms-albumshop.iml
  albumshop/build.gradle
  albumshop/src/main/java/bangshop/music/controller/OrderStorageController.java
  albumshop/src/main/java/bangshop/music/model/dao/OrderStorageMapper.java
  albumshop/src/main/java/bangshop/music/model/service/OrderStorageService.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
  albumshop/src/test/java/bangshop/music/controller/jhTest.java
Labels: documentation, Feature

#56 bug/ 창고관리자에서 앨범재고 view bug 오류
  albumshop/src/main/java/bangshop/music/model/dto/AlbumStorageDTO.java
  albumshop/src/main/java/bangshop/music/model/dto/OrderDTO.java
  albumshop/src/main/java/bangshop/music/view/menu/StoreManagerView.java
  albumshop/src/main/resources/sql/mapper/jh-query.xml
Labels: bug, update

#59 insert stock_out
  albumshop/src/main/java/bangshop/music/controller/OrderController.java
  albumshop/src/main/java/bangshop/music/model/dao/OrderMapper.java
  albumshop/src/main/java/bangshop/music/model/service/OrderService.java
  albumshop/src/main/java/bangshop/music/model/service/SearchService.java
  albumshop/src/main/resources/mybatis-config.xml
  albumshop/src/main/resources/sql/mapper/db-query.xml
  albumshop/src/main/resources/sql/mapper/order-mapper.xml
  albumshop/src/main/resources/sql/mapper/sc-query.xml
  albumshop/src/main/resources/sql/mapper/sc2-query.xml
Labels: update

#60 feature display all album
  albumshop/src/main/java/bangshop/music/controller/SearchController.java
  albumshop/src/main/java/bangshop/music/model/dao/SearchMapper.java
  albumshop/src/main/java/bangshop/music/model/service/SearchService.java
  albumshop/src/main/java/bangshop/music/view/menu/StorageAdminView.java
  albumshop/src/main/java/bangshop/music/view/result/SearchResultView.java
  albumshop/src/main/resources/mybatis-config.xml
  albumshop/src/main/resources/sql/mapper/sc-query.xml
Labels: Feature

#66 #65 db-test 코드 작성
  albumshop/src/test/java/bangshop/music/MabatisTemplateTest.java
  albumshop/src/test/java/bangshop/music/controller/dbTest.java
Labels: Feature

#68 #67 앨범 출고 에러 해결
  albumshop/src/main/java/bangshop/music/model/dto/AlbumStorageDTO.java
  albumshop/src/main/java/bangshop/music/model/service/DispatchService.java
  albumshop/src/main/resources/sql/mapper/album-storage-mapper.xml
  albumshop/src/main/resources/sql/mapper/order-mapper.xml
Labels: bug

#69 출고 상태에 따라 출력 변경
  albumshop/src/main/java/bangshop/music/controller/DispatchController.java
  albumshop/src/main/java/bangshop/music/model/dto/StockOutAndStorageDTO.java
  albumshop/src/main/resources/sql/mapper/yr-query.xml
Labels: Feature

#71 feature sort
  albumshop/src/main/java/bangshop/music/view/result/SearchResultView.java
Labels: update, Feature

#70 search 테스트 파일 업로드
  albumshop/build.gradle
  albumshop/src/test/java/bangshop/music/controller/jhTest.java
  albumshop/src/test/java/bangshop/music/controller/scTest.java
  albumshop/src/test/java/bangshop/music/controller/yrTest.java
Labels: Feature

#76 fix insert stock out bug
  albumshop/src/main/java/bangshop/music/controller/OrderController.java
  albumshop/src/main/java/bangshop/music/view/result/SearchResultView.java
Labels: bug
